version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: project-management-db
    environment:
      POSTGRES_DB: project_management
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"  # Changed from 5432 to 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: